name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    - name: Store AWS Credentials Securely
        run: |
          echo "AWS_ACCOUNT_ID=973508469163" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=AKIA6FKNAMGV4S7E3O7I" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=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" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # --- Docker Build & Push ---
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/hello-world-app:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # --- Terraform ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve

